import "../styles/globals.scss";
import "../styles/css-reset.css";
import type { Metadata } from "next";

import Footer from "@/components/Footer/Footer";
import Nav from "@/components/Nav/Nav";

export const metadata: Metadata = {
  title: "SVO Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
